# escape=`

FROM mcr.microsoft.com/mssql/server:2019-latest
EXPOSE 1433/tcp
SHELL ["powershell", "-command"]
RUN New-Item -ItemType Directory C:\Backup
RUN New-Item -ItemType Directory C:\Data
RUN powershell -Command Import-Module -name Pester


